# NUMPY


In [8]:
import numpy as np  # Importing the numpy library

# Correcting the array creation by using a list of lists
a = np.array([[1, 2, 3],
              [4, 5, 6]])  
a.shape 

(2, 3)

In [10]:
import numpy as np
a = np.array([1,2,3,4,5,6])

a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

In [21]:
a[5]

6

In [25]:
a[2:5]

array([3, 4, 5])

In [24]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a
a[2,1]



10

In [28]:
a.ndim

a.shape

len(a.shape) == a.ndim

a.size

a.dtype

np.empty(2)

np.arange(4)

array([0, 1, 2, 3])

In [42]:
arr = np.array([2,1,5,3,7,4,6,8,2])
np.sort(arr)

array([1, 2, 2, 3, 4, 5, 6, 7, 8])

In [56]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([8,8,8,8])

np.concatenate((a,b,c))
x= a+b+c
x

array([14, 16, 18, 20])

In [62]:
array_eg = np.array([[[0, 1, 2, 3], [4, 5, 6, 7]],[[0, 1, 2, 3],[4, 5, 6, 7]],
 [[0 ,1 ,2, 3],[4, 5, 6, 7]]])
array_eg.ndim

3

In [64]:
array_eg.size

24

In [66]:
array_eg.shape

(3, 2, 4)

In [14]:
x = np.array([2,1,5,3,7,4,6,8])
np.sort(x)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
x

array([2, 1, 5, 3, 7, 4, 6, 8])

In [53]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [55]:
b = a.reshape(3,2)
print(b)


[[0 1]
 [2 3]
 [4 5]]


In [79]:
a1 = np.array([[1,1],[2,2]])
a2 = np.array([[3,3],[4,4]])
np.vstack((a1,a2))
#sorting vertically

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [77]:
np.hstack((a1,a2))
#sorting horizontally

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [81]:
x = np.arange(1,25).reshape(2,12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [99]:
np.hsplit(x,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [101]:
np.hsplit(x,(3,4))


[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [107]:
np.hsplit(x,(3,6))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5,  6],
        [16, 17, 18]]),
 array([[ 7,  8,  9, 10, 11, 12],
        [19, 20, 21, 22, 23, 24]])]

In [113]:
a=np.array([1,2,3,4])
a.sum()

10

In [121]:
b = np.array([[3,1],[2,2]])
b.sum()

8

In [123]:
b.sum(axis=0)

array([5, 3])

In [127]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

a.sum()

4.8595784

In [129]:
a.min()

0.05093587

In [131]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])